version: '3'

services:
  postgres-docker:
    image: postgres
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5555:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    user: "472"
    links:
      - postgres-docker
    volumes:
      - ./grafana_data:/var/lib/grafana
    networks:
      - network
    depends_on:
      - postgres-docker

networks:
  network:
    driver: bridge