{
 "title": "Dashboard",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "language_name", "label": "Language", "query": "Kotlin" }
  ]
 },
 "panels": [
  {
   "title": "Days of code",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct date) from languages\nwhere $__timeFilter(date)"
    }
   ]
  },
  {
   "title": "Percentage days of code",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select (count(distinct date)::decimal/('${__to:date:YYYY-MM-DD}'::date - '${__from:date:YYYY-MM-DD}')*100)::int as percentage from languages\nwhere $__timeFilter(date)"
    }
   ]
  },
  {
   "title": "Average hours of code",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select (sum(hours)/('${__to:date:YYYY-MM-DD}'::date - '${__from:date:YYYY-MM-DD}'::date)) from languages\nwhere date BETWEEN '${__from:date}' and '${__to:date}'"
    }
   ]
  },
  {
   "title": "Total hours of code",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select sum(hours) from languages\nwhere date BETWEEN '${__from:date}' and '${__to:date}'"
    }
   ]
  },
  {
   "title": "Total by Language",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select sum(hours) as hours, to_char(date, 'YYYY-MM') as month from languages\nwhere $__timeFilter(date) and name = '$language_name'\ngroup by month\norder by month"
    }
   ]
  },
  {
   "title": "Total",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(hours) as hours, name from languages\nwhere $__timeFilter(date)\ngroup by name\norder by hours desc"
    }
   ]
  }
 ]
}